CONFIG_ZMK_KEYBOARD_NAME="Corne Boy"

CONFIG_ZMK_DISPLAY=y
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

CONFIG_ZMK_STUDIO=y

CONFIG_NICE_OLED_WIDGET_RAW_HID=y
CONFIG_NICE_OLED_WIDGET_RAW_HID_LAYOUT=n
CONFIG_NICE_OLED_WIDGET_RAW_HID_TIME=n
CONFIG_NICE_OLED_WIDGET_RAW_HID_VOLUME=n
CONFIG_KEYB_VIEWER=y

CONFIG_BT=y
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_BT_PERIPHERAL_PREF_LATENCY=0
CONFIG_BT_PERIPHERAL_PREF_MIN_INT=6
CONFIG_BT_PERIPHERAL_PREF_MAX_INT=6

CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=3600000
